services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 172033
      POSTGRES_DB: nilefy
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nilefy
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - path: .env
        required: true

volumes:
  postgres_data:
