version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nilefy
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nilefy
    restart: always
    expose:
      - 3000
    depends_on:
      - postgres
    env_file:
      - .env

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app  

volumes:
  postgres_data:
