const GRID_CELL_SIDE = 20;
const NUMBER_OF_COLUMNS = 32;
const ROW_HEIGHT = 5;
const ROOT_NODE_ID = 'ROOT';
const PREVIEW_NODE_ID = 'PREVIEW';
export {
  GRID_CELL_SIDE,
  NUMBER_OF_COLUMNS,
  ROW_HEIGHT,
  ROOT_NODE_ID,
  PREVIEW_NODE_ID,
};
