name: build-and-push-docker-image

on:
  push:
    branches:
      - "main"
      - "feat/docker-action"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract release tag
        id: extract_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build and push as latest version
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nagynabil/nilefy:latest
      - name: Build and push as ${{ env.RELEASE_TAG }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nagynabil/nilefy:${{ env.RELEASE_TAG }}
