name: build-and-push-docker-image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Build and push as latest version
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nagynabil/nilefy:latest
      - name: Build and push as ${{ steps.tagName.outputs.tag }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nagynabil/nilefy:${{ env.RELEASE_TAG }}
